# server-config
server:
  port: 80
  shutdown: graceful
  servlet:
    context-path: /
  undertow:
    worker-threads: 512
    max-http-post-size: 20MB

# spring-config
spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  application:
    name: carpool-api
  lifecycle:
    timeout-per-shutdown-phase: 30s
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/carpool?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&rewritebatchedstatements=true
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-test-query: SELECT 1
      pool-name: carpool
      max-lifetime: 1800000
      connection-init-sql: SET NAMES utf8mb4
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    enabled: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    request-context-attribute: request
    suffix: .html
    template-loader-path: classpath:/templates/
    settings:
      classic_compatible: true
      number_format: 0.##
  web:
    resources:
      add-mappings: false
  sql:
    init:
      continue-on-error: false